### ISSUE TITLE
Add changelog and new release

### ISSUE THREAD

**Issue by szlin** [kochstefan/usbauth-all#1]
Hi,

After seeing your [RFP in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880983), I'd be happy to package usbauth-all into Debian archive.

Could you add changelog and make a new release in each package with version 1.0 (perhaps)?

Thanks.

SZ

**Comment by kochstefan** [comment]
Hi szlin,

thanks for packaging usbauth.

I have added a NEWS file for libusbauth-configparser, usbauth and usbauth-notifier.

The NEWS file contains the same information as debian/changelog.

Thanks

Stefan
